### PR TITLE
Properly register cached proxies autoloader + allow readonly cache dir.

### LINKED ISSUE #232: cached proxies are still regenerated on fly even if dumped
**Ecotone version(s) affected**: 1.108.1

**Description**  
Continuation of https://github.com/ecotoneframework/ecotone-dev/issues/217

Now `cache:warmup` Symfony command properly generates proxy classes in `<cache-dir>/ecotone`, however they are still generated on fly.

**How to reproduce**  
0. Set up a Symfony project with Ecotone.
1. Make `<cache-dir>/ecotone` readonly
2. Comment or remove `Assert::isTrue(is_writable($cacheDirectoryPath), ...)` in `MessagingSystemConfiguration`. By the way, this check prevents me from having a readonly cache dir, which I would like to have after I dumped all proxies via cache:warmup. Dunno what to do about it, I suggest just removing it altogether - if the cache dir is not writable at the moment of writing a proxy class, it will tell you anyway.
3. Launch `php bin/console list` or `php bin/console ecotone:list`.

You'll get an error Cannot rename `Cannot rename "/tmp/ProxyManagerGeneratedProxy__PM__EcotoneMessagingGatewayConsole...`.

**Possible Solution**  
See https://github.com/Ocramius/ProxyManager/blob/2.15.x/docs/tuning-for-production.md

Basically we have to register the proxy autoloader before attempting to use proxies. Otherwise they are regenerated each time as now.

I added `spl_autoload_register($this->getConfiguration()->getProxyAutoloader())` to `ProxyFactory::createProxyClassWithAdapter()` as a proof of concept, and proxies stopped being regenerated each time. And it worked with the readonly cache dir (to have fully immutable project dir).

I remember about PRs I have agreed to do in the earlier discussions BTW :D

### PR DESCRIPTION
**Pull request by someniatko**
should fix #232

### CODE REVIEW

File: packages/Ecotone/src/Messaging/Config/MessagingSystemConfiguration.php [hunk 1]
```diff
@@ -872,6 +868,10 @@ public static function cleanCache(ServiceCacheConfiguration $serviceCacheConfigu
     private static function deleteFiles(string $target, bool $deleteDirectory): void
     {
         if (is_dir($target)) {
+            Assert::isTrue(
```
Comment (dgafka) [inline packages/Ecotone/src/Messaging/Config/MessagingSystemConfiguration.php:871]: This method is recursive, so we can check the permission once at the beginning in `cleanCache` method

File: packages/Ecotone/src/Messaging/Handler/Gateway/ProxyFactory.php [hunk 2]
```diff
@@ -26,6 +29,9 @@ class ProxyFactory
 {
     public const REFERENCE_NAME = 'gatewayProxyConfiguration';
 
+    private static ?AutoloaderInterface $registeredAutoloader = null;
```
Comment (dgafka) [inline packages/Ecotone/src/Messaging/Handler/Gateway/ProxyFactory.php:32]: Hmm I even think that we could remove the static, as ProxyFactory can be a shared instance from DI. 

However as this is from outside, let's keep static to avoid potential situation, where DI will provide new instance on each fetch, which would lead to memory leaks.

Comment (dgafka) [inline packages/Ecotone/src/Messaging/Handler/Gateway/ProxyFactory.php:32]: Hmm I even think that we could remove the static, as ProxyFactory can be a shared instance from DI. 

However as this is from outside, let's keep static to avoid potential situation, where DI will provide new instance on each fetch, which would lead to memory leaks.

Comment (dgafka) [reply packages/Ecotone/src/Messaging/Handler/Gateway/ProxyFactory.php:32]: @jlabedo any thoughts on this?

File: packages/Ecotone/src/Messaging/Handler/Gateway/ProxyFactory.php [hunk 3]
```diff
@@ -77,4 +80,26 @@ public function createWithCurrentConfiguration(string $referenceName, ContainerI
...
+        if (self::$registeredAutoloader) {
+            // another ProxyFactory instance may have already registered an autoloader.
+            // this should not happen normally, but just in case we will unload
+            // the old autoloader.
+            spl_autoload_unregister(self::$registeredAutoloader);
+        }
+
+        self::$registeredAutoloader = $this->getConfiguration()->getProxyAutoloader();
+        spl_autoload_register(self::$registeredAutoloader);
+        $this->autoloaderRegistered = true;
```
Comment (dgafka) [inline packages/Ecotone/src/Messaging/Handler/Gateway/ProxyFactory.php:103]: What was reasoning to introduce `autoloaderRegistered` instead of checking if `registeredAutoloader` is already assigned?

**Review by dgafka — COMMENTED** [review]
Minor comments :)

File: packages/Ecotone/src/Messaging/Handler/Gateway/ProxyFactory.php (hunk 2 above)
Comment (jlabedo) [reply packages/Ecotone/src/Messaging/Handler/Gateway/ProxyFactory.php:32]: Agree with avoiding static, but I think it is acceptable before à better solution. 
There is a test with 2 booted messaging systems in the same process (microservices) : static property could lead to strange behavior, but it is working... 
A better solution would be to register the autoloader in the boot méthod provided by frameworks, and unregister in the terminate méthod, as it is done in doctrine for instance. But we would have to handle this in test cases.

File: packages/Ecotone/src/Messaging/Config/MessagingSystemConfiguration.php (hunk 1 above)
Comment (someniatko) [reply packages/Ecotone/src/Messaging/Config/MessagingSystemConfiguration.php:871]: that's exactly why I've decided to check them everytime, the parent dir might be writable, but a child one - not, for some reason (an external script may have modified permissions).

File: packages/Ecotone/src/Messaging/Handler/Gateway/ProxyFactory.php (hunk 3 above)
Comment (someniatko) [reply packages/Ecotone/src/Messaging/Handler/Gateway/ProxyFactory.php:103]: to avoid re-registering autoloader for the same ProxyFactory instance.

File: packages/Ecotone/src/Messaging/Handler/Gateway/ProxyFactory.php (hunk 2 above)
Comment (someniatko) [reply packages/Ecotone/src/Messaging/Handler/Gateway/ProxyFactory.php:32]: > can be a shared instance from DI

unless it's a singleton, I believe we can't be 100% sure about that

File: packages/Ecotone/src/Messaging/Handler/Gateway/ProxyFactory.php (hunk 3 above)
Comment (someniatko) [reply packages/Ecotone/src/Messaging/Handler/Gateway/ProxyFactory.php:103]: if we check the static property only, each time a ProxyFactory client wants to create a proxy, we will unregister and then register the same autoloader, which is suboptimal in my opinion, which I hope you'll share too :)

File: packages/Ecotone/src/Messaging/Handler/Gateway/ProxyFactory.php (hunk 2 above)
Comment (jlabedo) [reply packages/Ecotone/src/Messaging/Handler/Gateway/ProxyFactory.php:32]: if we are not 100% sure, if 2 autoloaders are registered it is not à big issue. Before, every test case was registering it's own autoloader without unregistering it, leading to hundreds of those and the memory leak.

Comment (dgafka) [reply packages/Ecotone/src/Messaging/Handler/Gateway/ProxyFactory.php:32]: Yep, if we can't be sure if it's singleton, then in Message Consumer scenario, that would lead to creating a lot of them and memory leak.

I agree that's good enough solution for now :)

File: packages/Ecotone/src/Messaging/Handler/Gateway/ProxyFactory.php (hunk 3 above)
Comment (jlabedo) [reply packages/Ecotone/src/Messaging/Handler/Gateway/ProxyFactory.php:103]: Ok, I understood your point @someniatko. By doing that you cannot have two messaging systems running in the same process right ?

Comment (someniatko) [reply packages/Ecotone/src/Messaging/Handler/Gateway/ProxyFactory.php:103]: Not sure about what do you mean. If two ProxyFactories are used in the same PHP process, they will unregister each other's autoloader and register their own when necessary.

Comment (someniatko) [reply packages/Ecotone/src/Messaging/Handler/Gateway/ProxyFactory.php:103]: ah, I see, it won't work as intended in all cases. I'll update the relevant code.

**Comment by dgafka** [comment]
Cool stuff, thanks :)
